// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XerShade.Website.Core.Data;

#nullable disable

namespace XerShade.Website.Core.Data.Migrations
{
    [DbContext(typeof(DataDbContext))]
    [Migration("20240425061340_AddOptionsTable")]
    partial class AddOptionsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("XerShade.Website.Core.Data.Models.Option", b =>
                {
                    b.Property<int>("OptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OptionId"));

                    b.Property<bool>("AutoLoad")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OptionName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OptionValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("OptionId");

                    b.HasIndex("OptionName")
                        .IsUnique();

                    b.ToTable("CoreOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
